AllCops:
  Exclude:
    - db/**
    - db/migrate/**
    - bin/**

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - config/**/*
    - spec/**/*

Documentation:
  Enabled: false
